# Generated by Django 5.0.6 on 2024-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_shops_productstore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("cosmetics", "beauty product"),
                    ("stationery", "study product"),
                ],
                max_length=250,
            ),
        ),
    ]
