# Generated by Django 5.0.6 on 2024-06-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birth_date",
            field=models.DateField(auto_now=True),
        ),
    ]
